server:
  port: 7777
spring:
  application:
    name: eureka-server
eureka:
  client:
    #是否将自己注册到Eureka Server，默认为true。因为当前应用就是Eureka Server，所以需要设置成false。
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。因为本例是一个单点的Eureka Server，不需要同步其他Eureka Server节点数据，所以设置为false。
    fetch-registry: false
    service-url:
      #设置的是与Eureka Server的交互地址，查询和注册服务都依赖这个地址，如果有多个可以使用英文逗号分隔。
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${server.port}/eureka/
  instance:
    hostname: ${EUREKA_ZONE_HOST:localhost}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000
